items:
- uid: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException
  href: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException.yml
  name: RuntimeBinderException
  fullName: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException
  type: Class
  source:
    remote: &o0
      branch: master
      repo: https://github.com/dotnet/corefx.git
    path: src/Microsoft.CSharp/src/Microsoft/CSharp/RuntimeBinder/RuntimeBinderException.cs
    startLine: 12
  summary: >-
    Represents an error that occurs while processing a dynamic bind in the C# runtime binder. Exceptions of this type differ from [Microsoft.CSharp.RuntimeBinder.RuntimeBinderInternalCompilerException](Microsoft.CSharp.RuntimeBinder.RuntimeBinderInternalCompilerException.yml) in that

    [Microsoft.CSharp.RuntimeBinder.RuntimeBinderException](Microsoft.CSharp.RuntimeBinder.RuntimeBinderException.yml) represents a failure to bind in the sense of a usual compiler error, whereas [Microsoft.CSharp.RuntimeBinder.RuntimeBinderInternalCompilerException](Microsoft.CSharp.RuntimeBinder.RuntimeBinderInternalCompilerException.yml)

    represents a malfunctioning of the runtime binder itself.
  syntax:
    content:
      CSharp: public class RuntimeBinderException
  inheritance:
  - id: Exception
    name: Exception
    isExternal: true
  id: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException
  children:
  - Microsoft.CSharp.RuntimeBinder.RuntimeBinderException.#ctor
  - Microsoft.CSharp.RuntimeBinder.RuntimeBinderException.#ctor(System.String)
  - Microsoft.CSharp.RuntimeBinder.RuntimeBinderException.#ctor(System.String,Exception)
- uid: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException.#ctor
  href: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException.yml
  name: RuntimeBinderException()
  fullName: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException.RuntimeBinderException()
  type: Constructor
  source:
    remote: *o0
    path: src/Microsoft.CSharp/src/Microsoft/CSharp/RuntimeBinder/RuntimeBinderException.cs
    startLine: 17
  summary: Initializes a new instance of the [Microsoft.CSharp.RuntimeBinder.RuntimeBinderException](Microsoft.CSharp.RuntimeBinder.RuntimeBinderException.yml) class.
  syntax:
    content:
      CSharp: 'public RuntimeBinderException(): base ()'
    parameters: []
  id: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException.#ctor
- uid: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException.#ctor(System.String)
  href: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException.yml
  name: RuntimeBinderException(string)
  fullName: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException.RuntimeBinderException(string)
  type: Constructor
  source:
    remote: *o0
    path: src/Microsoft.CSharp/src/Microsoft/CSharp/RuntimeBinder/RuntimeBinderException.cs
    startLine: 26
  summary: Initializes a new instance of the [Microsoft.CSharp.RuntimeBinder.RuntimeBinderException](Microsoft.CSharp.RuntimeBinder.RuntimeBinderException.yml) class with a specified error message.
  syntax:
    content:
      CSharp: 'public RuntimeBinderException(string message): base (message)'
    parameters:
    - id: message
      type:
        id: System.String
        name: System.String
        isExternal: true
      description: The error message that explains the reason for the exception.
  id: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException.#ctor(System.String)
- uid: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException.#ctor(System.String,Exception)
  href: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException.yml
  name: RuntimeBinderException(string, Exception)
  fullName: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException.RuntimeBinderException(string, Exception)
  type: Constructor
  source:
    remote: *o0
    path: src/Microsoft.CSharp/src/Microsoft/CSharp/RuntimeBinder/RuntimeBinderException.cs
    startLine: 37
  summary: >-
    Initializes a new instance of the [Microsoft.CSharp.RuntimeBinder.RuntimeBinderException](Microsoft.CSharp.RuntimeBinder.RuntimeBinderException.yml) class with a specified error message

    and a reference to the inner exception that is the cause of this exception.
  syntax:
    content:
      CSharp: 'public RuntimeBinderException(string message, Exception innerException): base (message, innerException)'
    parameters:
    - id: message
      type:
        id: System.String
        name: System.String
        isExternal: true
      description: The error message that explains the reason for the exception.
    - id: innerException
      type:
        id: Exception
        name: Exception
        isExternal: true
      description: The exception that is the cause of the current exception, or a null reference if no inner exception is specified.
  id: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException.#ctor(System.String,Exception)
